theme: jekyll-theme-minimal
title: University of Zurich Master Thesis Template
description: University of Zurich Master Thesis Template (Universität Zürich Masterarbeit Vorlage) in RMarkdown and Latex in accordance to Bestimmungen zur Masterarbeit an der Philosophischen Fakultät der Universtät Zürich (UZH).
show_downloads: true
